# Generated by Django 3.2.4 on 2021-08-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210816_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='laptop_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
