# Generated by Django 3.2.4 on 2021-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210816_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='admission_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='laptop_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room_number',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default=20, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
