# Generated by Django 3.2.4 on 2021-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210910_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenyan', 'KENYAN'), ('Ugandan', 'UGANDAN'), ('Rwandan', 'RWANDAN'), ('South Sudan', 'SOUTH SUDAN')], default='Kenyan', max_length=15),
        ),
    ]
