# Generated by Django 3.2.4 on 2021-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'FEMALE'), ('Male', 'MALE'), ('Others', 'OTHERS')], default='Female', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('English', 'ENGLISH'), ('Swahili', 'SWAHILI')], default='English', max_length=15),
        ),
    ]
